sudo: required

language: go

services:
  - docker

script:
- ./build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push harrymartland/orderly-badger;
    fi